# Azure Storage Deploy

name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

# Set MyRunNumber
variables:
  MyRunNumber: '1.0.0-CI+$(Build.BuildNumber)'

trigger:
  - none

pool:
  vmImage: windows-latest

steps:
# Build Info
- script: echo $(MyRunNumber) # display MyRunNumber
- script: echo $(Build.BuildNumber) # display Run Number
- script: echo '$(Build.BuildNumber)' # outputs customized build number like project_def_master_20200828.1

# ARM Template - Deployment
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
      # Options: 'Resource Group', 'Management Group', 'Subscription'
    azureResourceManagerConnection: 'Dev_Azure_10002_CloudSandbox3(239c71f8-a24e-41d1-96f6-b4f834a1f615)'
      # ex - 'Dev_Azure_10002_CloudSandbox3(239c71f8-a24e-41d1-96f6-b4f834a1f615)'
    action: 'Create Or Update Resource Group'
      # Options: 'Create Or Update Resource Group', 'DeleteRG'
    resourceGroupName: 'JoePOC1'
      # Azure Resource Group name
    location: 'East US 2'
      # ex - 'East US 2'
    templateLocation: 'URL of the file'
      # Options: 'URL of the file', 'Linked Artifact'
    csmFileLink: 'https://raw.githubusercontent.com/a130138/01_TemplateRepo/main/01_AzStorage/01_AzStorageAccount/01_Deploy/01_Deploy/azuredeploy.json'
      # azuredeploy.json location (ensure using 'raw' URL for github)
    deploymentMode: 'Incremental'
      # Options:  'Incremental','Validation','Complete'
