# Azure Storage Acct Deploy via TF
variables:
  ##########"Json & ARM Variables"################## 
  - name: AzLoc 
    value: East US 2 
    # Azure location; i.e. - 'East US 2' 
  - name: AzArmConnection 
    value: Dev_Azure_10002_CloudSandbox3(239c71f8-a24e-41d1-96f6-b4f834a1f615) 
    # Azure ARM connection; i.e. - 'Dev_Azure_10002_CloudSandbox3(239c71f8-a24e-41d1-96f6-b4f834a1f615)' 
  - name: AzRgName 
    value: JoePOC1 
    # Azure resource group name
  - name: AzDir
    value: $(System.DefaultWorkingDirectory)/01_AzStorage/03_TF
  - name: AzSub
    value: 239c71f8-a24e-41d1-96f6-b4f834a1f615
pool:
    vmImage: ubuntu-latest
trigger:
    - none
steps:
- checkout: self
  persistCredentials: true
- task: TerraformCLI@0
  inputs:
    command: 'init'
    backendType: 'azurerm'
    backendServiceArm: '$(AzArmConnection)'
    backendAzureRmSubscriptionId: '$(AzSub)'
    backendAzureRmResourceGroupName: '$(AzRgName)'
    allowTelemetryCollection: false
    workingDirectory: '$(AzDir)'
- task: TerraformCLI@0
  inputs:
    command: 'fmt'
    backendType: 'azurerm'
    backendServiceArm: '$(AzArmConnection)'
    backendAzureRmSubscriptionId: '$(AzSub)'
    backendAzureRmResourceGroupName: '$(AzRgName)'
    allowTelemetryCollection: false
    workingDirectory: '$(AzDir)'
- task: TerraformCLI@0
  inputs:
    command: 'validate'
    backendType: 'azurerm'
    backendServiceArm: '$(AzArmConnection)'
    backendAzureRmSubscriptionId: '$(AzSub)'
    backendAzureRmResourceGroupName: '$(AzRgName)'
    allowTelemetryCollection: false
    workingDirectory: '$(AzDir)'
- task: TerraformCLI@0
  inputs:
    command: 'plan'
    environmentServiceName: '$(AzArmConnection)'
    providerAzureRmSubscriptionId: '$(AzSub)'
    backendAzureRmResourceGroupName: '$(AzRgName)'
    allowTelemetryCollection: false
    workingDirectory: '$(AzDir)'
- task: TerraformCLI@0
  inputs:
    command: 'apply'
    environmentServiceName: '$(AzArmConnection)'
    providerAzureRmSubscriptionId: '$(AzSub)'
    backendAzureRmResourceGroupName: '$(AzRgName)'
    allowTelemetryCollection: false
    workingDirectory: '$(AzDir)'