# Az Storage Create - Test

name: $(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r)

trigger:
  - none

pool:
  vmImage: ubuntu-latest

variables:
  - name:  rgn
    value:  JoePOC1

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Dev_Azure_10002_CloudSandbox3(239c71f8-a24e-41d1-96f6-b4f834a1f615)'
    subscriptionId: '239c71f8-a24e-41d1-96f6-b4f834a1f615'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '${{ variables.rgn }}'
    location: '$(Location)'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/a130138/01_TemplateRepo/main/00_TEST/azuredeploy.json'
    # csmParametersFileLink: 'https://raw.githubusercontent.com/a130138/01_TemplateRepo/main/00_TEST/azuredeploy.parameters.json'
    # overrideParameters: '-storageName jsizzle'
    deploymentMode:
     'Incremental'
     # Complete
     # Validation
    deploymentName: 'DeployPipelineTest'
