# Az Storage Deploy - Test

name: $(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r)

trigger:
  - none

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group' #Options:"Resource Group","Subscription","Management Group"
    azureResourceManagerConnection: 'Dev_Azure_10002_CloudSandbox3(239c71f8-a24e-41d1-96f6-b4f834a1f615)'
    action: 'Create Or Update Resource Group' #Options:"Create Or Update Resource Group","DeleteRG"
    resourceGroupName: $(resourceGroupName)
    location: $(location)
    templateLocation: 'URL of the file' #Options:"URL of the file","Linked Artifacts"
    csmFileLink: 'https://raw.githubusercontent.com/a130138/01_TemplateRepo/main/00_TEST/azuredeploy.json'
    deploymentMode: 'Incremental' #Options:Incremental,Complete,Validation
    deploymentName: 'deploytest'