# Azure Storage Deploy

trigger:
  - none

variables:
  - group: "AzVarGroupOne"

pool:
  vmImage: windows-latest

steps:

# ARM Template - Deployment
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
      # Options: 'Resource Group', 'Management Group', 'Subscription'
    azureResourceManagerConnection: 'Dev_Azure_10002_CloudSandbox3(239c71f8-a24e-41d1-96f6-b4f834a1f615)'
      # ex - 'Dev_Azure_10002_CloudSandbox3(239c71f8-a24e-41d1-96f6-b4f834a1f615)'
    action: 'Create Or Update Resource Group'
      # Options: 'Create Or Update Resource Group', 'DeleteRG'
    resourceGroupName: 'JoePOC1'
      # Azure Resource Group name
    location: 'East US 2'
      # ex - 'East US 2'
    templateLocation: 'URL of the file'
      # Options: 'URL of the file', 'Linked Artifact'
    csmFileLink: 'https://raw.githubusercontent.com/a130138/01_TemplateRepo/main/01_AzStorage/01_AzStorageAccount/01_Deploy/01_Deploy/azuredeploy.json'
      # azuredeploy.json location (ensure using 'raw' URL for github)
    deploymentMode: 'Incremental'
      # Options:  'Incremental','Validation','Complete'
