# AZ Storage Removal

trigger:
- none
pool:
  vmImage: ubuntu-latest
steps:  
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # PowerShell command:
      
       Remove-AzStorageAccount -ResourceGroupName "JoePOC1" -Name "storagevqqxiy7ee6xlg"