# PowerShell:  Azure NSG Deploy POC

trigger:
  - none
pool:
  vmImage: windows-latest
steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Dev_Azure_10002_CloudSandbox3(239c71f8-a24e-41d1-96f6-b4f834a1f615)'
    subscriptionId: '239c71f8-a24e-41d1-96f6-b4f834a1f615'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'JoePOC1'
    location: 'east us 2'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/a130138/01_TemplateRepo/main/04_AzNSG/01_Deploy/template.json'
    deploymentMode: 'Incremental'
    deploymentName: 'Az_NSG_Poc'
