# PowerShell:  Azure NSG Deploy POC

trigger:
  - none
pool:
  vmImage: windows-latest
steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: '$(azureResourceManagerConnection)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(resourceGroupName)'
    location: '$(location)'
    templateLocation: 'URL of the file'
    csmFileLink: '$(csmParametersFileLink)'
    deploymentMode: 'Incremental'
    deploymentName: '$(deploymentName)'
