# Azure Firewall Network Rule Deploy via TF

trigger:
    - none
pool:
    name: windows-latest

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'
- task: TerraformCLI@0
  inputs:
    command: 'init'
    allowTelemetryCollection: false
