# Azure Firewall Network Rule Deploy via TF

pool:
    vmImage: windows-latest
trigger:
    - none
steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'
- task: TerraformCLI@0
  inputs:
    command: 'init'
    allowTelemetryCollection: false
