# Title:  Azure Storage Account Deploy
# About:  Creates new repo folder with updated json variables, deploys to Az Portal
# Required:  Update variables section prior to deploy

variables:
##########"Azure Info"######################
  - name: AzCategory
    value: AzStorage
    # Azure Cateogory; i.e. - AzStorage, AzNSG, AzFirewall, etc; for repo folder setup
  - name: AzItem
    value: AzStorageAccount
    # Azure Item for category entered; i.e. - AzStorageAccount, AzStorageBlob, etc; for repo folder setup
  - name: AzRepoFolder
    value: $(System.DefaultWorkingDirectory)\01_$(AzCategory)\01_$(AzItem)
    # Azure repo folder path based on AzCategory\AzItem; i.e. - $(System.DefaultWorkingDirectory)\01_$(AzCategory)\01_$(AzItem)
  - name:  AzDestinationFileJSON
    value: $(AzRepoFolder)\01_Deploy\$(AzItem).$(AzStorageName).$(Build.BuildNumber)\azuredeploy.json
    # Setup of new json file
##########"Json & ARM Variables"##################
  - name: AzStorageName
    value: varstest2
    # name of new Azure storage account; i.e. - 'azstorageacct' (must be lowercase/no special chars)
  - name: AzTagEnv
    value: POC
    # Azure 'Environment' tag
  - name: AzTagOwn
    value: joseph cropper
    # Azure 'Owner' tag
  - name: AzSkuName
    value: Premium_LRS
    # Azure storage sku name; i.e. - 'Premium_LRS'
  - name: AzSkuTier
    value: Premium
    # Azure storage tier; i.e. - 'Premium'
  - name: AzLoc
    value: East US 2
    # Azure location; i.e. - 'East US 2'
  - name: AzKind
    value: Storage
    # Azure storage account type; i.e. - 'Storage'
  - name: AzArmConnection
    value: Dev_Azure_10002_CloudSandbox3(239c71f8-a24e-41d1-96f6-b4f834a1f615)
    # Azure ARM connection; i.e. - 'Dev_Azure_10002_CloudSandbox3(239c71f8-a24e-41d1-96f6-b4f834a1f615)'
  - name: AzRgName
    value: JoePOC1
    # Azure resource group name
##########"Repo Info"########################
  - name: GitJsonTemplate
    value:  'https://github.com/Azure/azure-quickstart-templates/blob/master/quickstarts/microsoft.storage/storage-account-create/azuredeploy.json'
  - name: GitRepoBranch
    value: _a130138_01_TemplateRepo
    # Repo branch main/master name; i.e. - '_a130138_01_TemplateRepo'
  - name: GitUserName
    value: a130138_tr1
    # Repo user name; i.e. - 'a130138_tr1'
  - name: GitUserEmail
    value: a130138_tr1@amerisourcebergen.com
    # Repo user email; i.e. - 'a130138_tr1@amerisourcebergen.com'

trigger:
  - none
pool:
  vmIMage: windows-latest
steps:
    - checkout: self
      persistCredentials: true
    - task: PowerShell@2
      inputs:
        targetType: inline
        script: |
          # Folder and files setup #
          Write-Host "#############################"
          Write-Host "Create new timestamped folder"
          New-Item $(AzRepoFolder)\01_Deploy -ItemType Directory -Name $(AzItem).$(AzStorageName).$(Build.BuildNumber)
          Write-Host "#############################"
          Write-Host "Copy json template to new timestamped folder"
          Copy-Item -Path $(GitJsonTemplate) -Destination $(AzRepoFolder)\01_Deploy\$(AzItem).$(AzStorageName).$(Build.BuildNumber)
          Write-Host "#############################"
          Write-Host "Save copy of azure-pipelines.yml"
          Copy-Item -Path $(AzRepoFolder)\03_Deploy_Test\azure-pipelines-1.yml -Destination $(AzRepoFolder)\01_Deploy\$(AzItem).$(AzStorageName).$(Build.BuildNumber)
    - task: PowerShell@2
      inputs:
        targetType: inline
        script: |
          # Inject variables from above #
          Write-Host "#############################"
          Write-Host "Update json variables"
          (Get-Content $(AzDestinationFileJSON)) | Foreach-Object {
              $_ -replace '@@AzStorageName@@', '$(AzStorageName)' `
                -replace '@@AzTagEnv@@', '$(AzTagEnv)' `
                -replace '@@AzTagOwn@@', '$(AzTagOwn)' `
                -replace '@@AzSkuName@@', '$(AzSkuName)' `
                -replace '@@AzSkuTier@@','$(AzSkuTier)' `
                -replace '@@AzLoc@@','$(AzLoc)' `
                -replace '@@AzKind@@','$(AzKind)' `
              } | Set-Content $(AzDestinationFileJSON)
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
          # Options:  Resource Group, Management Group, Subscription; cannot set variable(s)
        azureResourceManagerConnection: '$(AzArmConnection)'
          # Format example:  'Dev_Azure_10002_CloudSandbox3(239c71f8-a24e-41d1-96f6-b4f834a1f615)'
        action: 'Create Or Update Resource Group'
          # Options:  DeleteRG, Create or Update Resource Group; cannot set variable(s)
        resourceGroupName: '$(AzRgName)'
          # Azure Resource Group name
        location: '$(AzLoc)'
          # Azure location
        templateLocation: 'Linked artifact'
          # options:  Linked artifact, URL of the file; cannot set variable(s)
        csmFile: '$(Build.Repository.LocalPath)\01_$(AzCategory)\01_$(AzItem)\01_Deploy\$(AzItem).$(AzStorageName).$(Build.BuildNumber)\azuredeploy.json'
          # Location of azuredeploy.json; use 'raw' link for github repo & URL of the file
        deploymentMode: Incremental
          # Options:  Incremental, Validation, Complete; cannot set variable(s)
    - task: CmdLine@2
      inputs:
        script: |
          echo "####################"
          echo "Git push"
          echo "####################"
          cd $(System.DefaultWorkingDirectory)\$(GitRepoBranch)
          git init
          git config --global user.email "$(GitUserEmail)"
          git config --global user.name "$(GitUserName)"
          git fetch
          git checkout -b main
          git add .
          git commit -m "My commit message"
          git push origin HEAD:main