# Azure Storage Account Deploy

name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

# Set MyRunNumber
variables:
  MyRunNumber: '1.0.0-CI+$(Build.BuildNumber)'

trigger:
  - none

pool:
  vmImage: windows-latest

steps:
# Build Info
- script: echo $(MyRunNumber) # display MyRunNumber
- script: echo $(Build.BuildNumber) # display Run Number
- script: echo '$(Build.BuildNumber)' # outputs customized build number like project_def_master_20200828.1

# ARM Template Copy and Save
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      (Get-Contents $(System.DefaultWorkingDirectory)) -replace '','' | Set-Contents $(System.DefaultWorkingDirectory)
      Get-Contents $(System.DefaultWorkingDirectory)

# ARM Template Update
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.

# ARM Template Deployment
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Dev_Azure_10002_CloudSandbox3(239c71f8-a24e-41d1-96f6-b4f834a1f615)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'JoePOC1'
    location: 'East US 2'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/a130138/01_TemplateRepo/main/01_AzStorage/01_AzStorageAccount/01_Deploy/01_Deploy/azuredeploy.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/a130138/01_TemplateRepo/main/01_AzStorage/01_AzStorageAccount/01_Deploy/01_Deploy/azuredeploy.parameters.json'
    deploymentMode:
        Incremental
      ##  Validation
      ##  Complete

# Update Git Repo
- task: CmdLine@2  
  inputs:
    script: |
      git init
      git config --global user.email "a130138_tr1@amerisourcebergen.com"
      git config --global user.name "a130138_tr1"
      git fetch
      git checkout -b main
      git add .
      git commit -m "commit message"
      git push origin HEAD:main